In [3]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import linear_kernel

In [6]:
df = pd.read_csv('/dataset/shopee_reviews_purchase.csv')
df

,Unnamed: 0,user_id,product_id,rating,product_name_x,cmt_date,shop_id,variation_x,product_quality,processed_comment
0,0,0,0,4,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-06 12:28:25,0,Simple,4.0,mùi hương ko bít dành cho da tùy da công da an...
1,1,1,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-03 12:18:12,0,Simple,5.0,mùi nhẹ dành cho da mọi loại da công_dụng rửa ...
2,2,2,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-05 04:57:08,0,Simple,5.0,công_dụng rửa mặt_hàng giao rất nhanh sản_phẩm...
3,3,3,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-06 12:07:48,0,Simple,5.0,lần thứ 2 mua sp simple thì ai cũng biết lành_...
4,4,4,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2022-12-31 06:21:50,0,Simple,5.0,mua lần hai rồi dùng rất thích mọi người nên m...
...,...,...,...,...,...,...,...,...,...,...
369094,369094,115066,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-07-12 15:47:54,11,one_variation,5.0,mua nhiều lần ròi nên rất yên_tâm chính hãng
369095,369095,304704,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-10-11 10:01:38,11,one_variation,5.0,spham dùng ok
369096,369096,304705,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-08-14 05:28:51,11,one_variation,5.0,giao hàng cũng k nhanh lắm hãng này thì mình d...
369097,369097,304706,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-03-23 12:25:23,11,one_variation,5.0,đóng gói đẹp giao hàng nhanh
369098,369098,304707,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-04-07 09:06:41,11,one_variation,5.0,không hợp với da_khô không hợp với da_khô khôn...

In [7]:
df['user_id'].value_counts()

30112     20
133622    19
268589    16
54348     15
56572     15
          ..
113099     1
113100     1
113101     1
113102     1
304707     1
Name: user_id, Length: 304708, dtype: int64

In [8]:
df.columns

Index(['Unnamed: 0', 'user_id', 'product_id', 'rating', 'product_name_x',
       'cmt_date', 'shop_id', 'variation_x', 'product_quality',
       'processed_comment'],
      dtype='object')

In [9]:
df['cmt_date'] = pd.to_datetime(df['cmt_date'])

In [10]:
df_sorted = df.sort_values(by = ['user_id', 'cmt_date'])

In [11]:
df_sorted

,Unnamed: 0,user_id,product_id,rating,product_name_x,cmt_date,shop_id,variation_x,product_quality,processed_comment
0,0,0,0,4,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-06 12:28:25,0,Simple,4.0,mùi hương ko bít dành cho da tùy da công da an...
1,1,1,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-03 12:18:12,0,Simple,5.0,mùi nhẹ dành cho da mọi loại da công_dụng rửa ...
2,2,2,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-05 04:57:08,0,Simple,5.0,công_dụng rửa mặt_hàng giao rất nhanh sản_phẩm...
793,793,3,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2022-01-18 04:51:54,0,Simple,5.0,shop đóng_gói chắc_chắn có xốp chưa sử_dụng nh...
3,3,3,0,5,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,2023-01-06 12:07:48,0,Simple,5.0,lần thứ 2 mua sp simple thì ai cũng biết lành_...
...,...,...,...,...,...,...,...,...,...,...
369093,369093,304703,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-09-01 16:15:22,11,one_variation,5.0,mai má em gửi lên được 39 kg nhá vườn này vàng...
369095,369095,304704,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-10-11 10:01:38,11,one_variation,5.0,spham dùng ok
369096,369096,304705,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-08-14 05:28:51,11,one_variation,5.0,giao hàng cũng k nhanh lắm hãng này thì mình d...
369097,369097,304706,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-03-23 12:25:23,11,one_variation,5.0,đóng gói đẹp giao hàng nhanh
369098,369098,304707,2235,5,Sữa Rửa Mặt Senka Làm Sạch Sâu & Dưỡng Sáng Hồ...,2022-04-07 09:06:41,11,one_variation,5.0,không hợp với da_khô không hợp với da_khô khôn...

In [12]:
index = df_sorted.groupby(['user_id', 'product_id'])['cmt_date'].idxmax()
df_no_dup = df_sorted.loc[index, ['user_id', 'product_id', 'cmt_date']].sort_values(by=['user_id', 'cmt_date'], ascending=False)
df_no_dup

        user_id  product_id            cmt_date
369098   304707        2235 2022-04-07 09:06:41
369097   304706        2235 2022-03-23 12:25:23
369096   304705        2235 2022-08-14 05:28:51
369095   304704        2235 2022-10-11 10:01:38
369093   304703        2235 2022-09-01 16:15:22
...         ...         ...                 ...
4             4           0 2022-12-31 06:21:50
3             3           0 2023-01-06 12:07:48
2             2           0 2023-01-05 04:57:08
1             1           0 2023-01-03 12:18:12
0             0           0 2023-01-06 12:28:25

[338044 rows x 3 columns]

In [13]:
list_user = df_no_dup['user_id'].value_counts().index[:3952]
df_purchase = df_no_dup[df_no_dup['user_id'].isin(list_user)]
df_purchase

        user_id  product_id            cmt_date
368653   295796        2221 2022-12-21 06:46:28
357355   295796        1886 2022-11-18 06:39:16
358799   295796        1951 2022-09-19 07:23:34
350845   290595        1768 2022-12-13 13:23:02
353053   290595        1814 2022-11-12 12:03:30
...         ...         ...                 ...
242559      254         587 2023-01-01 14:03:31
257         254           0 2022-08-17 03:59:49
40           40           0 2022-12-20 13:03:12
3688         40           1 2022-12-20 13:03:12
93092        40         159 2022-12-20 13:03:12

[12763 rows x 3 columns]

# product data

In [15]:
df_prod = pd.read_csv('/dataset/shopee_product.csv')
df_prod

,avg_star,num_sold_time,price,variation,product_id,shop_id,product_name,brand,storage,origin,...,is_3_star,is_2_star,is_1_star,is_commented,is_image,num_rating,processed_description,expiry,send_from,image_path
0,4.8,185700,99000.0,one_variation,0,0,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,simple,18081.0,no_origin,...,1200,640,1600,42200,37900,66840,ưu_điểm nổi_trội sữa rửa mặt simple lành_tính ...,no_expiry,tp. hồ chí minh,111138057_8587034871.jpg
1,4.8,102600,99000.0,one_variation,1,0,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,9857.0,no_origin,...,709,320,723,22700,20400,36552,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,no_expiry,tp. hồ chí minh,111138057_8287055694.jpg
2,4.9,8100,244000.0,"['Phiên bản 2022 (80g)', 'Phiên bản 2023(100g)']",2,1,Sữa rửa mặt nam 30Shine phân phối chính hãng S...,Skin&Dr\t,95.0,Việt Nam,...,25,8,14,886,618,2644,sữa rửa mặt nam skin dr tràm trà 80 g cho da m...,24,hà nội,21080428_9335942418.mp4
3,4.9,3600,119000.0,one_variation,3,2,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,264.0,Việt Nam,...,3,0,1,92,63,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,24,hà nội,758111427_19601743242.mp4
4,4.8,26300,9900.0,one_variation,4,3,🌈🍒🍭 Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp D...,no_brand,987914.0,no_origin,...,150,52,61,3200,2300,6312,sỉ tốt 13 k c bao giá sl toàn_quốc ngại j khôn...,no_expiry,hà nội,107632788_3330988133.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,5.0,872,82000.0,"['Trắng ( Trắng da ).', 'Xanh ( collagen ) .',...",2239,1288,Sữa rửa mặt Kose Softymo Nhật Bản 220g,KOSÉ,1406.0,no_origin,...,1,0,0,126,121,270,sữa rửa mặt kose nhật bản best của best luôn a...,no_expiry,hà nội,294293046_5445658669.jpg
2240,5.0,43,205000.0,"['Tuýp 50ml', '200ml', '300ml', '400ml']",2240,1289,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...,La Roche-Posay,274.0,Pháp,...,0,0,0,3,3,12,sữa rửa mặt la efaclar foaming gel sẽ giúp ngă...,24,tp. hồ chí minh,97333460_10761076591.jpg
2241,4.9,823,75000.0,"['Hồng', 'Collagen', 'White']",2241,1290,Sữa rửa mặt Kose Softymo Nhật Bản 220g,no_brand,172.0,no_origin,...,2,0,2,124,106,218,sữa rửa mặt kose softymo là sản_phẩm sữa rửa m...,no_expiry,hà nội,315629668_3455178555.jpg
2242,5.0,1000,79000.0,one_variation,2242,407,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...,HATOMUGI,87.0,Nhật Bản,...,4,0,0,192,181,439,thương_hiệu reihaku hatomugi xuất_xứ nhật bản ...,no_expiry,tp. hồ chí minh,258099521_6677227750.jpg
2243,4.9,186,30000.0,one_variation,2243,821,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...,no_brand,5943.0,no_origin,...,0,0,0,8,9,35,sữa rửa mặt bơ aron thái lan 210 g dưỡng ẩm và...,no_expiry,thái nguyên,40662254_15079529213.jpg

In [16]:
df_prod.columns

Index(['avg_star', 'num_sold_time', 'price', 'variation', 'product_id',
       'shop_id', 'product_name', 'brand', 'storage', 'origin', 'type',
       'skin_kind', 'is_5_star', 'is_4_star', 'is_3_star', 'is_2_star',
       'is_1_star', 'is_commented', 'is_image', 'num_rating',
       'processed_description', 'expiry', 'send_from', 'image_path'],
      dtype='object')

In [17]:
df_prod['num_sold_time'] = df_prod['num_sold_time']/df_prod['num_sold_time'].max()

In [18]:
df_prod

,avg_star,num_sold_time,price,variation,product_id,shop_id,product_name,brand,storage,origin,...,is_3_star,is_2_star,is_1_star,is_commented,is_image,num_rating,processed_description,expiry,send_from,image_path
0,4.8,1.000000,99000.0,one_variation,0,0,Sữa rửa mặt Simple lành tính sạch thoáng - cho...,simple,18081.0,no_origin,...,1200,640,1600,42200,37900,66840,ưu_điểm nổi_trội sữa rửa mặt simple lành_tính ...,no_expiry,tp. hồ chí minh,111138057_8587034871.jpg
1,4.8,0.552504,99000.0,one_variation,1,0,Sữa rửa mặt Simple giúp kiềm dầu và ngừa mụn h...,simple,9857.0,no_origin,...,709,320,723,22700,20400,36552,ưu_điểm nổi_trội sữa rửa mặt simple giúp kiềm ...,no_expiry,tp. hồ chí minh,111138057_8287055694.jpg
2,4.9,0.043619,244000.0,"['Phiên bản 2022 (80g)', 'Phiên bản 2023(100g)']",2,1,Sữa rửa mặt nam 30Shine phân phối chính hãng S...,Skin&Dr\t,95.0,Việt Nam,...,25,8,14,886,618,2644,sữa rửa mặt nam skin dr tràm trà 80 g cho da m...,24,hà nội,21080428_9335942418.mp4
3,4.9,0.019386,119000.0,one_variation,3,2,Sữa rửa mặt nam RHYS MAN Rhys Coconut Fresh hư...,RHYS MAN,264.0,Việt Nam,...,3,0,1,92,63,180,chính hãng sữa rửa mặt nam rhys man rhys cocon...,24,hà nội,758111427_19601743242.mp4
4,4.8,0.141626,9900.0,one_variation,4,3,🌈🍒🍭 Sữa Rửa Mặt Senana Lấy Sạch Bụi Bẩn Giúp D...,no_brand,987914.0,no_origin,...,150,52,61,3200,2300,6312,sỉ tốt 13 k c bao giá sl toàn_quốc ngại j khôn...,no_expiry,hà nội,107632788_3330988133.jpg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,5.0,0.004696,82000.0,"['Trắng ( Trắng da ).', 'Xanh ( collagen ) .',...",2239,1288,Sữa rửa mặt Kose Softymo Nhật Bản 220g,KOSÉ,1406.0,no_origin,...,1,0,0,126,121,270,sữa rửa mặt kose nhật bản best của best luôn a...,no_expiry,hà nội,294293046_5445658669.jpg
2240,5.0,0.000232,205000.0,"['Tuýp 50ml', '200ml', '300ml', '400ml']",2240,1289,Sữa rửa mặt La Roche-Posay Effaclar chuyên dàn...,La Roche-Posay,274.0,Pháp,...,0,0,0,3,3,12,sữa rửa mặt la efaclar foaming gel sẽ giúp ngă...,24,tp. hồ chí minh,97333460_10761076591.jpg
2241,4.9,0.004432,75000.0,"['Hồng', 'Collagen', 'White']",2241,1290,Sữa rửa mặt Kose Softymo Nhật Bản 220g,no_brand,172.0,no_origin,...,2,0,2,124,106,218,sữa rửa mặt kose softymo là sản_phẩm sữa rửa m...,no_expiry,hà nội,315629668_3455178555.jpg
2242,5.0,0.005385,79000.0,one_variation,2242,407,Sữa Rửa Mặt Làm Sáng Da Reihaku Hatomugi Facia...,HATOMUGI,87.0,Nhật Bản,...,4,0,0,192,181,439,thương_hiệu reihaku hatomugi xuất_xứ nhật bản ...,no_expiry,tp. hồ chí minh,258099521_6677227750.jpg
2243,4.9,0.001002,30000.0,one_variation,2243,821,Sữa Rửa Mặt Bơ Aron Thái Lan 210g dưỡng ẩm và ...,no_brand,5943.0,no_origin,...,0,0,0,8,9,35,sữa rửa mặt bơ aron thái lan 210 g dưỡng ẩm và...,no_expiry,thái nguyên,40662254_15079529213.jpg

# Tf-idf

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word')
tfidf_matrix = tf.fit_transform(df_prod['processed_description'].values)
tfidf_matrix

<2244x9907 sparse matrix of type '<class 'numpy.float64'>'
	with 291619 stored elements in Compressed Sparse Row format>

In [ ]:
cosine_sim = linear_kernel(tfidf_matrix.toarray(), tfidf_matrix.toarray())

In [ ]:
cosine_sim

array([[1.        , 0.86702871, 0.16426628, ..., 0.20765181, 0.1960869 ,
        0.20611839],
       [0.86702871, 1.        , 0.17444194, ..., 0.21538401, 0.20885221,
        0.1976408 ],
       [0.16426628, 0.17444194, 1.        , ..., 0.15603771, 0.15400274,
        0.12778437],
       ...,
       [0.20765181, 0.21538401, 0.15603771, ..., 1.        , 0.23252974,
        0.24939219],
       [0.1960869 , 0.20885221, 0.15400274, ..., 0.23252974, 1.        ,
        0.17728698],
       [0.20611839, 0.1976408 , 0.12778437, ..., 0.24939219, 0.17728698,
        1.        ]])

# Phobert

In [ ]:
import torch
phobert_embedding = torch.load('/content_based_embeddings/shopee_description_full.pt', map_location=torch.device('cpu'))
phobert_embedding

tensor([[ 0.3056,  0.3391,  0.0153,  ..., -0.1492, -0.2377, -0.1039],
        [ 0.2375,  0.3576, -0.0450,  ..., -0.1682, -0.1502, -0.0557],
        [ 0.3590,  0.3596, -0.0635,  ..., -0.2159, -0.2076, -0.0722],
        ...,
        [ 0.2730,  0.2803, -0.0833,  ..., -0.0468, -0.2858, -0.1508],
        [ 0.0771,  0.3031,  0.0701,  ...,  0.1315, -0.1962, -0.1566],
        [ 0.1810,  0.4034, -0.1316,  ..., -0.1222, -0.2851, -0.2815]])

In [ ]:
phobert_embedding = phobert_embedding.numpy()

In [ ]:
phobert_cosine_sim = linear_kernel(phobert_embedding, phobert_embedding)
phobert_cosine_sim

array([[33.17023 , 32.759407, 29.255995, ..., 28.393545, 28.542774,
        27.325882],
       [32.759407, 34.73883 , 30.027039, ..., 28.991531, 28.915878,
        26.844913],
       [29.255995, 30.027039, 35.584118, ..., 28.167625, 29.500473,
        27.18119 ],
       ...,
       [28.393545, 28.991531, 28.167625, ..., 33.876717, 26.658104,
        24.595428],
       [28.542774, 28.915878, 29.500473, ..., 26.658104, 35.15274 ,
        25.26145 ],
       [27.325882, 26.844913, 27.18119 , ..., 24.595428, 25.26145 ,
        33.94019 ]], dtype=float32)

In [ ]:
phobert_cosine_sim = phobert_cosine_sim/phobert_cosine_sim.max()

# BLIP

In [ ]:
blip_embedding = np.load('/content_based_embeddings/blip_description_features.npy')
blip_embedding.shape

(2244, 256)

In [ ]:
blip_cosine_sim = linear_kernel(blip_embedding, blip_embedding)
blip_cosine_sim

array([[1.00000009, 0.78238339, 0.64783096, ..., 0.6515002 , 0.55851099,
        0.67196197],
       [0.78238339, 1.00000004, 0.64290851, ..., 0.5528154 , 0.56923144,
        0.58660923],
       [0.64783096, 0.64290851, 0.99999991, ..., 0.59742334, 0.53721511,
        0.68209254],
       ...,
       [0.6515002 , 0.5528154 , 0.59742334, ..., 1.00000012, 0.58583939,
        0.61067778],
       [0.55851099, 0.56923144, 0.53721511, ..., 0.58583939, 0.99999983,
        0.50948287],
       [0.67196197, 0.58660923, 0.68209254, ..., 0.61067778, 0.50948287,
        1.00000004]])

# OpenAI

In [ ]:
ada_embedding = np.load('/content_based_embeddings/ada2_description_features.npy')
ada_embedding.shape

(2244, 1536)

In [ ]:
ada_cosine_sim = linear_kernel(ada_embedding, ada_embedding)
ada_cosine_sim

array([[0.99999993, 0.96858564, 0.90709137, ..., 0.89254507, 0.8991291 ,
        0.90664586],
       [0.96858564, 1.00000005, 0.91341547, ..., 0.90923853, 0.91128875,
        0.91212209],
       [0.90709137, 0.91341547, 1.00000003, ..., 0.89681117, 0.90684496,
        0.91018609],
       ...,
       [0.89254507, 0.90923853, 0.89681117, ..., 0.9999999 , 0.90601334,
        0.89553158],
       [0.8991291 , 0.91128875, 0.90684496, ..., 0.90601334, 0.99999997,
        0.90762012],
       [0.90664586, 0.91212209, 0.91018609, ..., 0.89553158, 0.90762012,
        1.00000004]])

# Recommend

In [ ]:
id = df_prod['product_id']
indices = pd.Series(df_prod.index, index=df_prod['product_id'])

In [ ]:
id_name_dict = df_prod.set_index('product_id')['product_name'].to_dict()
name_id_dict = df_prod.set_index('product_name')['product_id'].to_dict()

In [ ]:
df_purchase.head(20)

            user_id   product_id            cmt_date
17639   871725073.0  18424418643 2022-11-10 12:58:22
32661   871725073.0  13006850994 2022-11-08 05:34:08
336339  871725073.0   4571147728 2022-10-08 12:25:49
8186    856269925.0   3330988133 2022-11-30 16:30:20
54614   856269925.0  13613809516 2022-11-30 16:26:40
12548   856269925.0  13995110712 2022-11-30 16:25:00
178960  837778630.0    864259092 2022-12-12 03:26:04
308560  837778630.0    864508598 2022-12-12 03:26:04
342484  837778630.0   6248814515 2022-08-14 04:39:30
324739  821645189.0   4118545903 2022-12-25 05:38:53
192601  821645189.0   7512993617 2022-12-25 05:38:53
183757  821645189.0  15368758361 2022-10-26 06:21:33
313853  800746234.0   2143729952 2023-01-07 14:51:54
29685   800746234.0   2227684389 2022-12-07 04:03:59
14952   800746234.0   9644340745 2022-10-16 02:02:25
83658   798039691.0  10898198132 2022-12-11 13:12:51
54645   798039691.0  13613809516 2022-12-11 13:12:51
139286  798039691.0  15202688577 2022-12-11 13:12:51
145428  795477892.0  14606883965 2022-11-03 12:40:50
67734   795477892.0   2495788192 2022-09-17 12:53:56

In [ ]:
def recommendations(product_id):
  idx = indices[product_id]
  sim_scores = list(enumerate(ada_cosine_sim[idx]))
  sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)
  sim_scores = sim_scores[1:101]
  df_indices = [i[0] for i in sim_scores]

  return id.iloc[df_indices].values[:10]

In [ ]:
result = recommendations(name_id_dict['[NỘI ĐỊA NHẬT] Sữa rửa mặt Kose Softymo Nhật Bản 220g'])

In [ ]:
id_name_dict[6312991956]

'Sữa rửa mặt Kose Softymo Nhật Bản 220g'

In [ ]:
for prod_id in result.tolist():
  print(id_name_dict[prod_id])

Bộ 2 hộp sữa rửa mặt gạo trắng da DABO RICE Hàn quốc 150ml/Hộp.
Sữa rửa mặt Hatomugi hạt ý dĩ
✅[Hàng Auth_Giá Sỉ] Gel rửa mặt, giảm nhờn, ngừa mụn ISIS Pharma Teen Derm Gel 150ml
[ Mẫu mới 2021 ] Sữa rửa mặt tạo bọt chiết xuất tơ tằm trắng Senka Perfect Whip 120g
✅[Chính hãng BABE] Gel rửa mặt dịu nhẹ Babe Stop AKN Purifying Cleansing Gel
Sữa rửa mặt KUMANO Hatomugi 130g dưỡng ẩm trắng da chiết xuất hạt ý dĩ Nhật - KONNI39
Sữa rửa mặt Kose Softymo Nhật Bản 220g
Bột rửa mặt cám gạo Thảo Dược (Hộp 120g)
Sữa Rửa Mặt Trà xanh Dabo Green Tea Foam Cleanser Hàn quốc 180ml/Hộp - HÀNG CHÍNH HÃNG
Sữa Rửa Mặt Cosrx Low PH Good Morning Gel Cleanser 150ml Hàn Quốc / Gel Rửa Mặt Cosrx chiết xuất trà xanh độ PH thấp

# Evaluation

In [ ]:
df_purchase

            user_id   product_id            cmt_date
17639   871725073.0  18424418643 2022-11-10 12:58:22
32661   871725073.0  13006850994 2022-11-08 05:34:08
336339  871725073.0   4571147728 2022-10-08 12:25:49
8186    856269925.0   3330988133 2022-11-30 16:30:20
54614   856269925.0  13613809516 2022-11-30 16:26:40
...             ...          ...                 ...
355694      41680.0    779015738 2020-07-14 09:10:27
270555      41680.0    845465208 2020-06-26 03:47:16
285631      40609.0   6312991956 2022-11-26 11:42:11
329971      40609.0   6934921300 2021-05-04 16:07:58
320036      40609.0   1215007085 2020-11-07 04:23:55

[12763 rows x 3 columns]

In [ ]:
train_index = [i for i in range(0, 12763, 3)]
val_index = [i for i in range(1, 12763, 3)]
test_index = [i for i in range(2, 12763, 3)]

In [ ]:
df_purchase.iloc[test_index, :]['user_id'].value_counts()

43174558.0     4
9767863.0      4
51889273.0     4
50949279.0     3
16517737.0     3
              ..
164773161.0    1
164599985.0    1
164526580.0    1
164474218.0    1
40609.0        1
Name: user_id, Length: 3952, dtype: int64

In [ ]:
print(len(train_index), len(val_index), len(test_index))

4255 4254 4254

In [ ]:
df_purchase['user_id'].value_counts()

9767863.0      12
43174558.0     12
730465643.0    11
51889273.0     10
375958177.0     9
               ..
157727194.0     3
157542045.0     3
157472516.0     3
157273584.0     3
40609.0         3
Name: user_id, Length: 3952, dtype: int64

In [ ]:
def PtopK(y_true, y_pred):
  if y_true in y_pred:
    return 1/len(y_pred)
  else:
    return 0
def RtopK(y_true, y_pred):
  if y_true in y_pred:
    return 1
  else:
    return 0

In [ ]:
def MRR(y_true, y_pred):
    if y_true not in y_pred:
        return 0

    rank = 0
    for index, value in enumerate(y_pred):
        if value == y_true:
            rank = 1 / (index + 1)
            break

    return rank

In [ ]:
def NDCG(y_true, y_pred, k=None):
    if y_true not in y_pred:
        return 0.0

    true_index = y_pred.index(y_true)
    ideal_sorted = sorted(y_pred, reverse=True)
    ideal_index = ideal_sorted.index(y_true)

    dcg = 1.0 / np.log2(true_index + 2)
    idcg = 1.0 / np.log2(ideal_index + 2)

    ndcg = dcg / idcg

    if k is not None:
        ideal_sorted = ideal_sorted[:k]
        y_pred = y_pred[:k]
        true_index = y_pred.index(y_true)
        ideal_index = ideal_sorted.index(y_true)
        dcg = 1.0 / np.log2(true_index + 2)
        idcg = 1.0 / np.log2(ideal_index + 2)
        ndcg = dcg / idcg

    return ndcg

In [ ]:
rtopk_val = []
rtopk_test = []
ptopk_val = []
ptopk_test = []
mrr_val = []
mrr_test = []
ndcg_val = []
ndcg_test = []

for user in df_purchase['user_id'].unique():
  temp = df_purchase[df_purchase['user_id']==user]
  x_val = temp.iloc[2, 1]
  y_val = temp.iloc[1, 1]
  y_val_pred = recommendations(x_val).tolist()
  rtopk_val.append(RtopK(y_val, y_val_pred))
  ptopk_val.append(PtopK(y_val, y_val_pred))
  mrr_val.append(MRR(y_val, y_val_pred))
  ndcg_val.append(NDCG(y_val, y_val_pred, 10))

  x_test = temp.iloc[1, 1]
  y_test = temp.iloc[0, 1]
  y_test_pred = recommendations(x_test).tolist()
  rtopk_test.append(RtopK(y_test, y_test_pred))
  ptopk_test.append(PtopK(y_test, y_test_pred))
  mrr_test.append(MRR(y_test, y_test_pred))
  ndcg_test.append(NDCG(y_test, y_test_pred, 10))

In [ ]:
def calculate_mean(numbers):
    if not numbers:
        return 0.0
    return sum(numbers) / len(numbers)

print('rtopk val', calculate_mean(rtopk_val))
print('rtopk test', calculate_mean(rtopk_test))
print('ptopk val',calculate_mean(ptopk_val))
print('ptopk test', calculate_mean(ptopk_test))
print('mrr val', calculate_mean(mrr_val))
print('mrr test', calculate_mean(mrr_test))
print('ndcg val', calculate_mean(ndcg_val))
print('ndcg test', calculate_mean(ndcg_test))

rtopk val 0.13866396761133604
rtopk test 0.16447368421052633
ptopk val 0.013866396761133732
ptopk test 0.01644736842105278
mrr val 0.05982454132125181
mrr test 0.07424410384936689
ndcg val 0.2214818743050516
ndcg test 0.2720800676147077

# Parameter finetunning

In [ ]:
score = [0.1*x for x in range(11)]
score

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [ ]:
def recommendations(product_id, scr_score, embedding):
  idx = indices[product_id]
  sim_scores = list(enumerate(embedding[idx]))
  sim_scores = sorted(sim_scores, key=lambda x:x[1], reverse=True)
  sim_scores = sim_scores[1:101]
  df_indices = [i[0] for i in sim_scores]

  luot_mua = df_prod.loc[df_indices, 'num_sold_time']
  temp = pd.DataFrame(sim_scores, columns = ['index', 'score'])
  temp.index=temp['index']
  temp.drop(['index'], axis=1, inplace=True)
  score = temp['score']*scr_score+luot_mua*(1-scr_score)
  score = score.sort_values(ascending=False)
  df_indices = score.index.values.tolist()

  return id.iloc[df_indices].values[:10]

In [ ]:
from tqdm import tqdm
index = 0
df = pd.DataFrame(columns = ['score_weight', 'popular_weight', 'rtopk val', 'rtopk test', 'ptopk val', 'ptopk test', 'mrr val', 'mrr test', 'ndcg val', 'ndcg test'])
for scr in tqdm(score):
  rtopk_val = []
  rtopk_test = []
  ptopk_val = []
  ptopk_test = []
  mrr_val = []
  mrr_test = []
  ndcg_val = []
  ndcg_test = []

  for user in df_purchase['user_id'].unique():
    temp = df_purchase[df_purchase['user_id']==user]
    x_val = temp.iloc[2, 1]
    y_val = temp.iloc[1, 1]
    y_val_pred = recommendations(x_val, scr, ada_cosine_sim).tolist()
    rtopk_val.append(RtopK(y_val, y_val_pred))
    ptopk_val.append(PtopK(y_val, y_val_pred))
    mrr_val.append(MRR(y_val, y_val_pred))
    ndcg_val.append(NDCG(y_val, y_val_pred, 10))

    x_test = temp.iloc[1, 1]
    y_test = temp.iloc[0, 1]
    y_test_pred = recommendations(x_test, scr, ada_cosine_sim).tolist()
    rtopk_test.append(RtopK(y_test, y_test_pred))
    ptopk_test.append(PtopK(y_test, y_test_pred))
    mrr_test.append(MRR(y_test, y_test_pred))
    ndcg_test.append(NDCG(y_test, y_test_pred, 10))
  dict_temp = {
      'score_weight': scr,
      'popular_weight': 1-scr,
      'rtopk val': calculate_mean(rtopk_val),
      'rtopk test': calculate_mean(rtopk_test),
      'ptopk val': calculate_mean(ptopk_val),
      'ptopk test': calculate_mean(ptopk_test),
      'mrr val': calculate_mean(mrr_val),
      'mrr test': calculate_mean(mrr_test),
      'ndcg val': calculate_mean(ndcg_val),
      'ndcg test': calculate_mean(ndcg_test)
  }
  df = pd.concat([df, pd.DataFrame(dict_temp, index=[index])], ignore_index=True)
  index += 1

100%|██████████| 11/11 [07:12<00:00, 39.31s/it]